@echo off

:RON

start notepad

start notepad

start notepad
start notepad

start notepad

start notepad
start notepad

start notepad

start notepad
start notepad

start notepad

start notepad
start notepad

start notepad

start notepad
start notepad

start notepad

start notepad
start notepad

start notepad

start notepad
start notepad

start notepad

start notepad
start notepad

start notepad

start notepad
start notepad

start notepad

start notepad
start notepad

start notepad

start notepad
start notepad

start notepad

start notepad
start notepad

start notepad

start notepad
start notepad

start notepad

start notepad
start notepad

start notepad

start notepad
start notepad

start notepad

start notepad
start notepad

start notepad

start notepad
start notepad

start notepad

start notepad
start notepad

start notepad

start notepad
start notepad

start notepad



start notepad

start notepad
start notepad

start notepad

start notepad
start notepad

start notepad

start notepad

start notepad

start notepad

start notepad
start notepad

start notepad

start notepad
start notepad

start notepad

start notepad
start notepad

start notepad

start notepad
start notepad

start notepad

start notepad
start notepad

start notepad

start notepad
start notepad

start notepad

start notepad
start notepad

start notepad

start notepad
start notepad

start notepad

start notepad
start notepad

start notepad

start notepad
start notepad

start notepad

start notepad
start notepad

start notepad

start notepad
start notepad

start notepad

start notepad
start notepad

start notepad

start notepad
start notepad

start notepad

start notepad
PAUSE
goto RON